export const ADD_LAND_LOADING = 'ADD_LAND_LOADING';
export const ADD_LAND_SUCCESS = 'ADD_LAND_SUCCESS';
export const ADD_LAND_FAILED = 'ADD_LAND_FAILED';

export const ADD_PRODUCTCATEGORY_LOADING = 'ADD_PRODUCTCATEGORY_LOADING';
export const ADD_PRODUCTCATEGORY_SUCCESS = 'ADD_PRODUCTCATEGORY_SUCCESS';
export const ADD_PRODUCTCATEGORY_FAILED = 'ADD_PRODUCTCATEGORY_FAILED';

export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const ADD_AGENT_LOADING = 'ADD_AGENT_LOADING';
export const ADD_AGENT_SUCCESS = 'ADD_AGENT_SUCCESS';
export const ADD_AGENT_FAILED = 'ADD_AGENT_FAILED';


export const ADD_FUTUREINVENTORY_LOADING = 'ADD_FUTUREINVENTORY_LOADING';
export const ADD_FUTUREINVENTORY_SUCCESS = 'ADD_FUTUREINVENTORY_SUCCESS';
export const ADD_FUTUREINVENTORY_FAILED = 'ADD_FUTUREINVENTORY_FAILED';

export const ADD_AVAILABLEINVENTORY_LOADING = 'ADD_AVAILABLEINVENTORY_LOADING';
export const ADD_AVAILABLEINVENTORY_SUCCESS = 'ADD_AVAILABLEINVENTORY_SUCCESS';
export const ADD_AVAILABLEINVENTORY_FAILED = 'ADD_AVAILABLEINVENTORY_FAILED';

export const ADD_CROP_LOADING = 'ADD_CROP_LOADING';
export const ADD_CROP_SUCCESS = 'ADD_CROP_SUCCESS';
export const ADD_CROP_FAILED = 'ADD_CROP_FAILED';

export const LIST_PRODUCT_LOADING = 'LIST_PRODUCT_LOADING';
export const LIST_PRODUCT_SUCCESS = 'LIST_PRODUCT_SUCCESS';
export const LIST_PRODUCT_FAILED = 'LIST_PRODUCT_FAILED';

export const LIST_PRODUCTCATEGORY_LOADING = 'LIST_PRODUCTCATEGORY_LOADING';
export const LIST_PRODUCTCATEGORY_SUCCESS = 'LIST_PRODUCTCATEGORY_SUCCESS';
export const LIST_PRODUCTCATEGORY_FAILED = 'LIST_PRODUCTCATEGORY_FAILED';
