export const ADD_LAND_LOADING = 'ADD_LAND_LOADING';
export const ADD_LAND_SUCCESS = 'ADD_LAND_SUCCESS';
export const ADD_LAND_FAILED = 'ADD_LAND_FAILED';

export const ADD_PRODUCTCATEGORY_LOADING = 'ADD_PRODUCTCATEGORY_LOADING';
export const ADD_PRODUCTCATEGORY_SUCCESS = 'ADD_PRODUCTCATEGORY_SUCCESS';
export const ADD_PRODUCTCATEGORY_FAILED = 'ADD_PRODUCTCATEGORY_FAILED';

export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const ADD_FUTUREINVENTORY_LOADING = 'ADD_FUTUREINVENTORY_LOADING';
export const ADD_FUTUREINVENTORY_SUCCESS = 'ADD_FUTUREINVENTORY_SUCCESS';
export const ADD_FUTUREINVENTORY_FAILED = 'ADD_FUTUREINVENTORY_FAILED';

export const ADD_AVAILABLEINVENTORY_LOADING = 'ADD_AVAILABLEINVENTORY_LOADING';
export const ADD_AVAILABLEINVENTORY_SUCCESS = 'ADD_AVAILABLEINVENTORY_SUCCESS';
export const ADD_AVAILABLEINVENTORY_FAILED = 'ADD_AVAILABLEINVENTORY_FAILED';